version: '3.8'

services:
  cv-maker-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv_maker_app
    ports:
      - "1420:1420"
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    command: npm run dev -- --host
