export const EDITOR_LIMITS = {
  MAX_LANGUAGES: 5,
  MAX_EXECUTIVE_SUMMARY_CHARS: 500,
  MAX_POSITION_SUMMARY_CHARS: 300,
  MAX_BULLET_CHARS: 250,
  MAX_PROJECT_DESC_CHARS: 250,
  MAX_PROJECT_TAGS: 6,
  MAX_CATEGORY_SKILLS: 8,
  MAX_SKILL_CATEGORIES: 6
} as const;
